# Source: metallb/templates/webhooks.yaml
apiVersion: batch/v1
kind: Job
metadata:
  name:  metallb-create-secret
spec:
  ttlSecondsAfterFinished: 5
  template:
    metadata:
      name:  metallb-create-secret
    spec:
      containers:
        - name: create
          image: jettech/kube-webhook-certgen:v1.5.2
          imagePullPolicy: IfNotPresent
          args:
            - create
            - --host=webhook-service.metallb-system.svc
            - --namespace=metallb-system
            - --secret-name=webhook-server-cert
            - --cert-name=tls.crt
            - --key-name=tls.key
      restartPolicy: OnFailure
      serviceAccountName: controller
      securityContext:
        runAsGroup: 2000
        runAsNonRoot: true
        runAsUser: 2000
