{{- if .Values.controller.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "metallb.controller.serviceAccountName" . }}
  labels:
    {{- include "metallb.labels" . | nindent 4 }}
    app.kubernetes.io/component: controller
  annotations:
  {{- if and .Values.webhooks.enable .Values.webhooks.patch.enabled (not .Values.webhooks.certManager.enabled) }}
    "helm.sh/hook": pre-install,pre-upgrade
  {{- end }}
  {{- with .Values.controller.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
{{- if .Values.speaker.serviceAccount.create }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "metallb.speaker.serviceAccountName" . }}
  labels:
    {{- include "metallb.labels" . | nindent 4 }}
    app.kubernetes.io/component: speaker
  {{- with .Values.speaker.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
